name: Laravel Pest Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing_db
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql, tokenizer, xml, ctype
          ini-values: date.timezone=UTC

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Copy .env for testing
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Configure Database in .env
        run: |
          php -r "file_put_contents('.env', str_replace('DB_DATABASE=laravel', 'DB_DATABASE=testing_db', file_get_contents('.env')));"
          php -r "file_put_contents('.env', str_replace('DB_USERNAME=', 'DB_USERNAME=root', file_get_contents('.env')));"
          php -r "file_put_contents('.env', str_replace('DB_PASSWORD=', 'DB_PASSWORD=root', file_get_contents('.env')));"

      - name: Clear config cache
        run: php artisan config:clear

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run Pest tests
        run: ./vendor/bin/pest --colors=always
